# Generated by Django 2.2.7 on 2019-11-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='air_quality_cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=200)),
                ('Category_of_ES', models.CharField(max_length=200)),
                ('SO2_Annual_average', models.IntegerField()),
                ('Air_quality_of_SO2', models.CharField(max_length=100)),
                ('NO2_Annual_average', models.IntegerField()),
                ('Air_quality_of_NO2', models.CharField(max_length=100)),
                ('PM10_Annual_average', models.IntegerField()),
                ('Air_quality_of_PM10', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='air_quality_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality', models.CharField(max_length=20)),
                ('PM10_low', models.IntegerField()),
                ('PM10_high', models.IntegerField()),
                ('PM2_5_low', models.IntegerField()),
                ('PM2_5_high', models.IntegerField()),
                ('NO2_low', models.IntegerField()),
                ('NO2_high', models.IntegerField()),
                ('O3_low', models.IntegerField()),
                ('O3_high', models.IntegerField()),
                ('CO_low', models.IntegerField()),
                ('CO_high', models.IntegerField()),
            ],
        ),
    ]
