# Generated by Django 2.2.5 on 2019-11-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191123_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_quality_cities',
            name='id',
        ),
        migrations.AlterField(
            model_name='air_quality_cities',
            name='City',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
